"""add currency and exchange_rate back

Revision ID: 020c2a7cfa52
Revises: bc89622583bb
Create Date: 2026-02-15 20:16:22.975476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020c2a7cfa52'
down_revision: Union[str, Sequence[str], None] = 'bc89622583bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_reports', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('financial_reports', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_reports', 'exchange_rate')
    op.drop_column('financial_reports', 'currency')
    # ### end Alembic commands ###
