"""add finacial_reports table

Revision ID: 12329c8a21e3
Revises: 17dc655ef1c7
Create Date: 2026-02-01 17:10:17.481588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12329c8a21e3'
down_revision: Union[str, Sequence[str], None] = '17dc655ef1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('dividend_start_year', sa.Integer(), nullable=True))
    op.alter_column('companies', 'api_trade_available_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'api_trade_available_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('companies', 'dividend_start_year')
    # ### end Alembic commands ###
