"""add_stock_prices_multipliers_and_company_price

Revision ID: 66b3844bc6d0
Revises: f0fd17d7697c
Create Date: 2026-03-07 20:07:13.651122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b3844bc6d0'
down_revision: Union[str, Sequence[str], None] = 'f0fd17d7697c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_stock_price_company_date')
    )
    op.create_index(op.f('ix_stock_prices_company_id'), 'stock_prices', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_prices_date'), 'stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_stock_prices_id'), 'stock_prices', ['id'], unique=False)
    op.create_table('multipliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('price_used', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('shares_used', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ltm_net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ltm_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ltm_dividends_per_share', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['financial_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', 'type', name='uq_multiplier_company_date_type')
    )
    op.create_index(op.f('ix_multipliers_company_id'), 'multipliers', ['company_id'], unique=False)
    op.create_index(op.f('ix_multipliers_date'), 'multipliers', ['date'], unique=False)
    op.create_index(op.f('ix_multipliers_id'), 'multipliers', ['id'], unique=False)
    op.create_index(op.f('ix_multipliers_report_id'), 'multipliers', ['report_id'], unique=False)
    op.add_column('companies', sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('companies', sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'price_updated_at')
    op.drop_column('companies', 'current_price')
    op.drop_index(op.f('ix_multipliers_report_id'), table_name='multipliers')
    op.drop_index(op.f('ix_multipliers_id'), table_name='multipliers')
    op.drop_index(op.f('ix_multipliers_date'), table_name='multipliers')
    op.drop_index(op.f('ix_multipliers_company_id'), table_name='multipliers')
    op.drop_table('multipliers')
    op.drop_index(op.f('ix_stock_prices_id'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_date'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_company_id'), table_name='stock_prices')
    op.drop_table('stock_prices')
    # ### end Alembic commands ###
