"""shares_outstanding_and_shares_used_to_bigint

Revision ID: 6e096f66805d
Revises: 66b3844bc6d0
Create Date: 2026-03-08 16:01:34.567418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e096f66805d'
down_revision: Union[str, Sequence[str], None] = '66b3844bc6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_reports', 'price_per_share',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('financial_reports', 'price_at_filing',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('financial_reports', 'shares_outstanding',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('financial_reports', 'total_assets',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=True)
    op.alter_column('financial_reports', 'total_liabilities',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=True)
    op.alter_column('financial_reports', 'current_assets',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=True)
    op.alter_column('financial_reports', 'current_liabilities',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=True)
    op.alter_column('financial_reports', 'equity',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=True)
    op.alter_column('financial_reports', 'revenue',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=True)
    op.alter_column('financial_reports', 'net_income',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=True)
    op.alter_column('multipliers', 'shares_used',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('multipliers', 'shares_used',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('financial_reports', 'net_income',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'revenue',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'equity',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'current_liabilities',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'current_assets',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'total_liabilities',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'total_assets',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'shares_outstanding',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('financial_reports', 'price_at_filing',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('financial_reports', 'price_per_share',
               existing_type=sa.Numeric(precision=15, scale=4),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
