"""add report metadata fields

Revision ID: a0aa9e10c35e
Revises: 020c2a7cfa52
Create Date: 2026-02-19 21:26:40.964843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0aa9e10c35e'
down_revision: Union[str, Sequence[str], None] = '020c2a7cfa52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_reports', sa.Column('period_type', sa.Enum('QUARTERLY', 'ANNUAL', 'SEMI_ANNUAL', name='periodtype', native_enum=False, length=20), nullable=False))
    op.add_column('financial_reports', sa.Column('fiscal_year', sa.Integer(), nullable=False))
    op.add_column('financial_reports', sa.Column('fiscal_quarter', sa.Integer(), nullable=True))
    op.add_column('financial_reports', sa.Column('accounting_standard', sa.Enum('IFRS', 'RAS', 'US_GAAP', 'UK_GAAP', 'OTHER', name='accountingstandard', native_enum=False, length=20), nullable=False))
    op.add_column('financial_reports', sa.Column('consolidated', sa.Boolean(), nullable=False))
    op.add_column('financial_reports', sa.Column('filing_date', sa.Date(), nullable=True))
    op.add_column('financial_reports', sa.Column('source', sa.Enum('MANUAL', 'COMPANY_WEBSITE', 'API', 'REGULATOR', 'OTHER', name='reportsource', native_enum=False, length=30), nullable=False))
    op.create_index(op.f('ix_financial_reports_accounting_standard'), 'financial_reports', ['accounting_standard'], unique=False)
    op.create_index(op.f('ix_financial_reports_fiscal_year'), 'financial_reports', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_reports_period_type'), 'financial_reports', ['period_type'], unique=False)
    op.create_unique_constraint('uq_financial_report', 'financial_reports', ['company_id', 'fiscal_year', 'fiscal_quarter', 'period_type', 'accounting_standard', 'consolidated'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financial_report', 'financial_reports', type_='unique')
    op.drop_index(op.f('ix_financial_reports_period_type'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_fiscal_year'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_accounting_standard'), table_name='financial_reports')
    op.drop_column('financial_reports', 'source')
    op.drop_column('financial_reports', 'filing_date')
    op.drop_column('financial_reports', 'consolidated')
    op.drop_column('financial_reports', 'accounting_standard')
    op.drop_column('financial_reports', 'fiscal_quarter')
    op.drop_column('financial_reports', 'fiscal_year')
    op.drop_column('financial_reports', 'period_type')
    # ### end Alembic commands ###
