"""fix

Revision ID: bc89622583bb
Revises: 564dd342f02a
Create Date: 2026-02-04 21:56:57.518027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc89622583bb'
down_revision: Union[str, Sequence[str], None] = '564dd342f02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_financial_reports_id'), 'financial_reports', ['id'], unique=False)
    op.drop_column('financial_reports', 'currency')
    op.drop_column('financial_reports', 'exchange_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_reports', sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('financial_reports', sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'RUB'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_financial_reports_id'), table_name='financial_reports')
    # ### end Alembic commands ###
