"""add price_at_filing field

Revision ID: f0fd17d7697c
Revises: a0aa9e10c35e
Create Date: 2026-02-23 13:19:11.225222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fd17d7697c'
down_revision: Union[str, Sequence[str], None] = 'a0aa9e10c35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_reports', sa.Column('price_at_filing', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_reports', 'price_at_filing')
    # ### end Alembic commands ###
